services:
  app:
    # Coolify will build the Dockerfile in your repo if it finds one
    image: 'ghcr.io/marceloarraes/astro-site:latest'
    container_name: astro-site-prod
    pull_policy: always
    ports:
      # Map your host port 4690 to the container's Nginx port 80
      - '4690:80'
    restart: unless-stopped