version: '3.8'
services:
  app:
    image: 'ghcr.io/marceloarraes/astro-site:latest'
    container_name: astro-site-prod
    pull_policy: always
    ports:
      - '4690:4321'
    restart: unless-stopped
